apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentx-deployment
spec:
  selector:
    matchLabels:
      app: studentx
  template:
    metadata:
      labels:
        app: studentx
    spec:
      containers:
      - name: studentx
        image: registry.tanzu.dk/ops2devops/studentx:v1
