apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentx-deployment
  namespace: studentx
spec:
  selector:
    matchLabels:
      app: studentx
  template:
    metadata:
      labels:
        app: studentx
    spec:
      containers:
      - name: studentx
        image: ghcr.io/tanzudk/ops2devops/5-k8s-1:master
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: studentx
spec:
  type: NodePort
  selector:
    app: studentx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010 # Remember to change to student number.

